;(function(){
if(!window.CW_MODULES)window.CW_MODULES={};
window.CW_MODULES['Brute Force']={
icon:"🔨",cat:"Auth Attack",col:"#ffcc44",
explain:["ATTACK: BRUTE FORCE  |  OCR 1.3.3(c)","━━━━━━━━━━━━━━━━━━━━━",
  "Automated tools test thousands of password combinations per second.",
  "8-char lowercase = 26^8 = 208 billion combos. MFA defeats this completely.",
  "Defences: account lockout, rate limiting, CAPTCHA, MFA."],
mutations:[
  {name:"Distributed botnet",label:"🌐 DISTRIBUTED",escMulti:1.4,spreadMult:1.3,userMult:1.5},
  {name:"Password spray",label:"🌊 SPRAY",escMulti:1.1,spreadMult:1.0,userMult:2.0},
  {name:"Script kiddie",label:"🎲 SCRIPT KIDDIE",escMulti:0.6,spreadMult:0.4,userMult:0.7}],
scenarios:[
 {id:"dictionary_attack",name:"Dictionary Attack",short:"Common password wordlist tested at high speed",
  escs:["Dictionary attack on login portal — top 10,000 passwords being tried",
        "Multiple accounts locked — some may be compromised",
        "ADMIN PASSWORD CRACKED — elevated access obtained"],
  escR:22,uMin:100,uMax:5000,spread:"Credential Stuffing",
  responses:[
   {id:"lockout_policy",name:"Enforce Account Lockout",team:"identity",baseDuration:16,
    ocrRef:"1.3.3(c)",effectiveness:90,scorePts:70,
    description:"Enforce account lockout after 5 failed attempts — blocking automated password guessing.",
    duringRisk:"Accounts being targeted remain at risk until lockout is enforced.",
    narrative:[
      "Identity Team deploying account lockout policy...",
      "Brute force works by trying many passwords rapidly — lockout stops it (OCR 1.3.3c).",
      "Setting lockout threshold: 5 failed attempts → 15-minute lockout.",
      "This forces attackers to wait 15 minutes per 5 attempts — computationally impractical.",
      "MFA would defeat brute force entirely — even with the correct password, a second factor is needed.",
      "Lockout policy deployed. Attack neutralised."],
    complications:[{at:.5,chance:.2,msg:"Legacy system not supporting lockout policy — manual override",extraTime:.35}],
    earlyFinish:{chance:.15,msg:"Lockout policy pre-configured — quick activation"}},
   {id:"rate_limit",name:"Rate Limit + CAPTCHA",team:"network",baseDuration:22,
    ocrRef:"1.3.3(c)",effectiveness:85,scorePts:65,
    description:"Throttle login attempts per IP and introduce CAPTCHA to block automated tools.",
    duringRisk:"Attack continues at reduced speed while rate limiting is deployed.",
    narrative:[
      "Network Team deploying login rate limiting and CAPTCHA challenges...",
      "Rate limiting: max 10 login attempts per IP per minute.",
      "CAPTCHA challenges require human interaction — automated tools cannot solve them.",
      "Bot traffic dropped by 99.7%. Remaining attempts hitting CAPTCHA wall."],
    complications:[{at:.4,chance:.2,msg:"Attacker using CAPTCHA bypass service — adjusting approach",extraTime:.3}],
    earlyFinish:{chance:.1,msg:"Simple rate limit effective — attacker not using bypass service"}},
   {id:"analyst_mfa",name:"Configure MFA Policy (YOU)",team:"analyst",baseDuration:40,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:120,
    description:"Implement multi-factor authentication — making brute force completely ineffective.",
    duringRisk:"You are unavailable for ~40 seconds.",
    narrative:["Configuring MFA policy for all authentication endpoints..."],
    complications:[],earlyFinish:{chance:.15,msg:"MFA provider already integrated — quick policy activation"},
    analystChallenge:{
      context:"You're implementing MFA to stop brute force attacks. Even if an attacker correctly guesses a password, MFA means they still can't log in.",
      question:"MFA defeats brute force because even a correct password isn't enough. What does MFA stand for?\n\n(Type the full phrase, 3 words):",
      ocrLink:"OCR 1.3.3(c): Multi-Factor Authentication (MFA) requires users to verify identity using two or more factors from different categories: something you KNOW (password), something you HAVE (phone/token), something you ARE (biometrics). Brute force can only attack 'something you know' — MFA makes that insufficient for access.",
      hint1:"It requires MORE THAN ONE way to verify who you are.",
      hint2:"MFA = ______-Factor Authentication. The blank is a word meaning 'more than one'.",
      hint3:"Multi-Factor Authentication — requiring a password PLUS a second factor (phone, fingerprint, etc.).",
      fullAnswer:"multi-factor authentication",
      checkFn:(s)=>{const l=s.toLowerCase();return l.includes("multi-factor")||l.includes("multifactor")||l==="mfa";}}}]},

 {id:"password_spray",name:"Password Spray Attack",short:"Top 3 passwords tried against every account — evades lockout",
  escs:["Password spray: 'Password1' tried against all 4,200 accounts",
        "47 accounts accessed via common passwords",
        "MULTIPLE ADMIN ACCOUNTS COMPROMISED"],
  escR:28,uMin:50,uMax:20000,spread:"Credential Stuffing",
  responses:[
   {id:"lockout",name:"Tighten Lockout Threshold",team:"identity",baseDuration:14,
    ocrRef:"1.3.3(c)",effectiveness:85,scorePts:65,
    description:"Reduce lockout threshold to 3 attempts to catch spray attacks that try only 1–2 passwords per account.",
    duringRisk:"Some accounts may be compromised before lockout is tightened.",
    narrative:[
      "Password spray uses only 1–2 passwords per account to evade standard lockout.",
      "Reducing lockout threshold from 10 to 3 attempts — catches spray pattern.",
      "Deploying alerting for accounts that have received even 1 failed login.",
      "Spray pattern blocked. Compromised accounts being identified for reset."],
    complications:[{at:.4,chance:.2,msg:"Attacker switched to 1 attempt per account — harder to detect",extraTime:.3}],
    earlyFinish:{chance:.1,msg:"Attack was using obvious timing pattern — quick detection"}},
   {id:"analyst_reset",name:"Force Password Resets (YOU)",team:"analyst",baseDuration:35,
    ocrRef:"1.3.3(c)",effectiveness:95,scorePts:110,
    description:"Identify all accounts using the top 100 common passwords and force immediate resets.",
    duringRisk:"You are unavailable for ~35 seconds.",
    narrative:["Running compromised password check against known common password list..."],
    complications:[],earlyFinish:{chance:.2,msg:"Most accounts used strong passwords — few resets needed"},
    analystChallenge:{
      context:"Password spray works because many users choose predictable passwords. You need to identify and reset accounts using the most common passwords.",
      question:"Password complexity rules require passwords to include uppercase, lowercase, numbers and symbols. This is called password __________. Type the missing word:",
      ocrLink:"OCR 1.3.3(c): Password COMPLEXITY requirements increase the keyspace attackers must search. A password using only lowercase letters (26 options per character) is vastly weaker than one using the full character set (95 options). Length also matters — each additional character multiplies the difficulty exponentially.",
      hint1:"It's a word meaning 'how complicated' something is.",
      hint2:"Simple = basic. Difficult = complex. Password ___________.",
      hint3:"COMPLEXITY — password complexity rules require mixing uppercase, lowercase, numbers and symbols to increase the difficulty of guessing or cracking.",
      fullAnswer:"complexity",
      checkFn:(s)=>s.trim().toLowerCase().includes("complex")}}]}
]};
})();
