;(function(){
if(!window.CW_MODULES)window.CW_MODULES={};
window.CW_MODULES['Phishing']={
icon:"✉",cat:"Social Engineering",col:"#ffaa00",
explain:["ATTACK: PHISHING  |  OCR SPEC: 1.3.3(c)","━━━━━━━━━━━━━━━━━━━━━",
  "Phishing sends emails impersonating trusted organisations to steal credentials.",
  "It exploits HUMAN PSYCHOLOGY — bypassing purely technical defences like firewalls.",
  "Covered in OCR 1.3.3(c): social engineering, threats to networks, defensive measures.",
  "Defences: email filtering, DNS blacklisting, user training, MFA."],
mutations:[
  {name:"Nation-state",label:"🏴 STATE-SPONSORED",escMulti:1.6,spreadMult:2.0,userMult:1.4},
  {name:"AI lures",label:"🤖 AI-ENHANCED",escMulti:1.3,spreadMult:1.1,userMult:1.2},
  {name:"Opportunistic",label:"🎲 OPPORTUNISTIC",escMulti:0.7,spreadMult:0.5,userMult:0.8}],
scenarios:[
 {id:"mass_campaign",name:"Mass Phishing Campaign",short:"Bulk emails sent to entire organisation",
  escs:["Phishing emails reaching all inboxes — credentials at risk",
        "Users clicking links — credential harvest underway",
        "ADMIN CREDENTIALS STOLEN — full network access obtained"],
  escR:28,uMin:5000,uMax:60000,spread:"Credential Stuffing",
  responses:[
   {id:"gateway_block",name:"Block at Email Gateway",team:"network",baseDuration:18,
    ocrRef:"1.3.3(c)",effectiveness:80,scorePts:60,
    description:"Filter and blacklist the sending domain at the email gateway, quarantining all matching emails.",
    duringRisk:"Users who already received emails remain vulnerable until notified.",
    narrative:[
      "Network Team accessing email gateway management console...",
      "Phishing emails impersonate trusted organisations to steal credentials — OCR 1.3.3(c).",
      "Email gateways check inbound mail against blacklists of known malicious domains.",
      "Tracing sending domain: suspicious-invoice-247.xyz — confirmed malicious registration.",
      "Blacklisting domain at DNS level. All subdomains included in filter.",
      "Existing delivered emails being flagged and quarantined. Users now protected from further lures."],
    complications:[{at:.5,chance:.25,msg:"Attacker using 3 sending domains — extending scan",extraTime:.35}],
    earlyFinish:{chance:.15,msg:"Single sending domain confirmed — faster than expected"}},
   {id:"full_response",name:"Full Incident Response",team:"identity",baseDuration:55,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:100,
    description:"Block the domain, notify all staff, force password resets on accounts that clicked.",
    duringRisk:"Attack continues for ~55s — more credentials may be harvested.",
    narrative:[
      "Identity Team coordinating full incident response...",
      "Phishing relies on users trusting fake emails — MFA defeats this even if passwords are stolen (1.3.3c).",
      "Broadcasting security alert: 'Do NOT click links in emails from invoice-247.xyz'.",
      "Cross-referencing click logs — identifying accounts that may have submitted credentials.",
      "Forcing immediate password resets on 47 at-risk accounts.",
      "Enabling MFA enforcement across organisation. Stolen passwords now useless to attackers.",
      "Incident documented. Awareness training scheduled."],
    complications:[{at:.5,chance:.2,msg:"Email click logs incomplete — manual audit required",extraTime:.3}],
    earlyFinish:{chance:.1,msg:"Staff responded quickly to alert — fewer accounts to reset"}},
   {id:"analyst_trace",name:"Trace Attack Infrastructure (YOU)",team:"analyst",baseDuration:38,
    ocrRef:"1.3.3(c)",effectiveness:95,scorePts:120,
    description:"Personally trace the attacker's sending infrastructure to identify and neutralise the full campaign.",
    duringRisk:"You will be unavailable to manage teams for ~38 seconds.",
    narrative:[
      "Examining email headers for true origin...",
      "Email spoofing abuses SMTP's lack of authentication. SPF and DKIM verify sender legitimacy.",
      "Social engineering exploits human psychology, not software — OCR 1.3.3(c) key concept."],
    complications:[],earlyFinish:{chance:.2,msg:"Attack infrastructure was poorly hidden — quick identification"},
    analystChallenge:{
      context:"You're examining the email headers of a suspicious message. The FROM field shows 'HMRC <tax@gov.uk>' but something's wrong.",
      question:"Which email header field reveals the TRUE IP address of the sending server?\n\nFormat: X-Originating-___",
      ocrLink:"OCR 1.3.3(c): Social engineering exploits human trust. SPF (Sender Policy Framework) and DKIM use DNS records to verify that a sending server is authorised to send email on behalf of a domain — preventing spoofing.",
      hint1:"Think about what uniquely identifies every device on a network. It's a two-letter abbreviation.",
      hint2:"Every device has an Internet Protocol address. The header field that shows the sender's real server is X-Originating-___ (3 letters).",
      hint3:"The answer is 'IP'. The full field is X-Originating-IP — it reveals the real server even when the FROM address is spoofed.",
      fullAnswer:"IP",
      checkFn:(s)=>s.trim().toUpperCase()==="IP"||s.trim().toUpperCase()==="X-ORIGINATING-IP"}}]},

 {id:"spear_phish",name:"Spear Phishing",short:"Targeted emails crafted for specific employees using personal detail",
  escs:["Targeted phishing at senior staff — admin credentials at risk",
        "Executive clicked — credential compromise likely",
        "C-SUITE CREDENTIALS STOLEN — board-level access obtained"],
  escR:22,uMin:10,uMax:500,spread:"Social Engineering",
  responses:[
   {id:"gateway_block",name:"Block Sending Domain",team:"network",baseDuration:14,
    ocrRef:"1.3.3(c)",effectiveness:75,scorePts:55,
    description:"Emergency blacklist the spoofed domain before more targets are lured.",
    duringRisk:"Targeted employees already contacted remain at risk.",
    narrative:[
      "Spear phishing uses personal detail (names, roles, recent projects) to appear legitimate.",
      "Unlike mass phishing, each email is crafted for ONE person — harder to detect automatically.",
      "DNS blacklist deployed. Malicious domain blocked at gateway."],
    complications:[{at:.5,chance:.2,msg:"Attacker using lookalike domain — extended blocking required",extraTime:.3}],
    earlyFinish:{chance:.15,msg:"Domain flagged by threat intelligence — pre-cached block applied"}},
   {id:"full_response",name:"Alert + Lock Targeted Accounts",team:"identity",baseDuration:40,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:90,
    description:"Directly contact and brief all targeted individuals, lock their accounts pending credential reset.",
    duringRisk:"Targeted individuals may act on the emails before being warned.",
    narrative:[
      "Identifying all 12 employees named in the spear phishing campaign...",
      "Spear phishing has a far higher click rate than mass phishing — OCR 1.3.3(c).",
      "Phone-calling each target directly: 'Do not click any HMRC email — this is an attack.'",
      "Locking accounts of those who may have already submitted credentials.",
      "Out-of-band verification protocol enforced for all password resets."],
    complications:[{at:.5,chance:.15,msg:"Two executives unreachable — escalating to PA",extraTime:.25}],
    earlyFinish:{chance:.1,msg:"All targets reached quickly via instant messaging"}},
   {id:"analyst_osint",name:"OSINT: Profile the Attacker (YOU)",team:"analyst",baseDuration:35,
    ocrRef:"1.3.3(c)",effectiveness:90,scorePts:110,
    description:"Use open-source intelligence to identify how the attacker gathered the personal information used in the spear phish.",
    duringRisk:"You are unavailable while profiling — ~35 seconds.",
    narrative:[
      "Examining the spear phish content for indicators of attacker intelligence gathering..."],
    complications:[],earlyFinish:{chance:.2,msg:"Attacker used publicly visible LinkedIn data — quickly identified"},
    analystChallenge:{
      context:"The spear phish email references the target's job title, recent project, and manager's name — all accurate. The attacker must have gathered this from somewhere.",
      question:"What term describes using publicly available information (social media, LinkedIn, company websites) to gather intelligence before an attack?\n\nType the 4-letter acronym:",
      ocrLink:"OCR 1.3.3(c): Social engineering — attackers exploit human trust. OSINT (Open Source INTelligence) means gathering information from public sources before attacking. This is why oversharing on professional networks creates security risk.",
      hint1:"It's a type of intelligence gathering using only public sources — not hacking.",
      hint2:"OSINT stands for Open Source IN_______ — a type of intelligence.",
      hint3:"The answer is OSINT — Open Source INTelligence. Attackers use LinkedIn, Twitter, company websites to gather details that make phishing emails more convincing.",
      fullAnswer:"OSINT",
      checkFn:(s)=>s.trim().toUpperCase()==="OSINT"||s.toLowerCase().includes("open source intelligence")}}]},

 {id:"whaling",name:"Whaling Attack",short:"CEO/CFO targeted for high-value financial fraud",
  escs:["CEO email impersonation detected — fraudulent wire transfer request sent",
        "Finance team processing fraudulent request — transfer imminent",
        "FRAUDULENT TRANSFER AUTHORISED — funds moved to attacker account"],
  escR:25,uMin:1,uMax:20,spread:"Social Engineering",
  responses:[
   {id:"emergency_alert",name:"Alert Finance Team",team:"identity",baseDuration:12,
    ocrRef:"1.3.3(c)",effectiveness:85,scorePts:65,
    description:"Immediately warn the finance team that the CEO email is impersonated — halt any pending transfers.",
    duringRisk:"Transfer may have already been approved in the seconds before alert.",
    narrative:[
      "Identity Team calling the finance director directly — bypassing email entirely.",
      "Whaling targets C-suite with tailored impersonation — OCR 1.3.3(c) CEO fraud example.",
      "Finance team alerted. Pending wire transfer of £240,000 halted.",
      "CEO impersonation domain blacklisted. Verification callback protocol activated."],
    complications:[{at:.5,chance:.2,msg:"Finance director travelling — reaching PA instead",extraTime:.3}],
    earlyFinish:{chance:.2,msg:"Finance director was already suspicious — quick resolution"}},
   {id:"trace_impersonation",name:"Trace Impersonation Domain (YOU)",team:"analyst",baseDuration:30,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:110,
    description:"Identify exactly how the CEO's email is being impersonated and permanently block the attack vector.",
    duringRisk:"You are unavailable for ~30 seconds.",
    narrative:["Examining email headers for impersonation technique...","DMARC, DKIM and SPF records being audited..."],
    complications:[],earlyFinish:{chance:.2,msg:"Simple display-name spoofing — quickly identified"},
    analystChallenge:{
      context:"The attacker is sending emails that appear to come from 'John Smith CEO <ceo@company.com>' but are actually from a different server. What email authentication standard publishes a list of authorised sending servers in DNS records?",
      question:"Which email authentication standard publishes AUTHORISED sending servers in DNS?\n\nType the 3-letter acronym:",
      ocrLink:"OCR 1.3.3(c): SPF (Sender Policy Framework) is a DNS record that lists which mail servers are allowed to send email on behalf of a domain. If an email comes from an unlisted server, it fails SPF and can be rejected — preventing domain spoofing.",
      hint1:"It's a 3-letter acronym for a DNS-based email authentication standard.",
      hint2:"Sender _____ Framework — fills in the blank with a word meaning 'policy' rules.",
      hint3:"SPF — Sender Policy Framework. A DNS TXT record listing authorised mail servers for a domain.",
      fullAnswer:"SPF",
      checkFn:(s)=>s.trim().toUpperCase()==="SPF"||s.toLowerCase().includes("sender policy")}}]}
]};
})();
