;(function(){
if(!window.CW_MODULES)window.CW_MODULES={};
window.CW_MODULES['Ransomware']={
icon:"🔒",cat:"Malware",col:"#ff3333",
explain:["ATTACK: RANSOMWARE  |  OCR 1.3.3(c) + 1.3.1(c)","━━━━━━━━━━━━━━━━━━━━━",
  "Ransomware encrypts files using asymmetric encryption — OCR 1.3.1(c).",
  "The PUBLIC key encrypts files. Only the attacker's PRIVATE key can decrypt them.",
  "Without the private key, decryption is computationally infeasible.",
  "WannaCry (2017): 200,000 systems, 150 countries, NHS cost £92M."],
mutations:[
  {name:"Double extortion",label:"⚠ DOUBLE EXTORTION",escMulti:1.4,spreadMult:1.5,userMult:1.2},
  {name:"Nation-state",label:"🏴 NATION-STATE",escMulti:1.8,spreadMult:2.5,userMult:1.6},
  {name:"RaaS gang",label:"💼 RAAS GANG",escMulti:1.3,spreadMult:1.8,userMult:1.3}],
scenarios:[
 {id:"network_worm",name:"Network Worm Ransomware",short:"Self-propagating — spreads automatically via network shares",
  escs:["Encryption active on infected workstation — files being locked",
        "Worm spread to file server — shared drives being encrypted",
        "DOMAIN CONTROLLER ENCRYPTED — entire organisation locked out"],
  escR:13,uMin:200,uMax:8000,spread:"Ransomware",
  responses:[
   {id:"isolate_contain",name:"Emergency Network Isolation",team:"security",baseDuration:16,
    ocrRef:"1.3.3(c)",effectiveness:85,scorePts:70,
    description:"Immediately isolate infected machines from the network to stop worm propagation. Fast but doesn't remove malware.",
    duringRisk:"Encryption continues on already-infected machines until kill-process is run.",
    narrative:[
      "Security Ops executing emergency network isolation protocol...",
      "Ransomware MUST be isolated immediately — every second = more files encrypted (1.3.3c).",
      "Infected workstation disconnected from network. Worm spread halted.",
      "Checking shared drives for encryption activity — monitoring file change rates.",
      "Isolation successful. Worm contained. Ready for kill-process phase."],
    complications:[{at:.5,chance:.3,msg:"Worm already on 3 additional machines — expanding isolation",extraTime:.4}],
    earlyFinish:{chance:.1,msg:"Single infection vector — isolated faster than expected"}},
   {id:"full_eradication",name:"Full: Isolate + Kill + Restore",team:"security",baseDuration:75,
    ocrRef:"1.3.3(c) + 1.3.1(c)",effectiveness:100,scorePts:100,
    description:"Complete response: isolate, terminate encryption process, restore from clean backups.",
    duringRisk:"75 seconds of active encryption — more files will be locked.",
    narrative:[
      "Security Ops executing full ransomware eradication procedure...",
      "STEP 1: Network isolation — worm propagation stopped.",
      "Ransomware uses asymmetric encryption: public key encrypts, private key decrypts (OCR 1.3.1c).",
      "Without the attacker's private key, encrypted files are computationally infeasible to recover.",
      "STEP 2: Terminating ransomware process — stopping active encryption.",
      "STEP 3: Deploying clean backup from last known-good snapshot.",
      "All files restored. Zero data loss. Incident contained."],
    complications:[{at:.5,chance:.25,msg:"Backup from 3 days ago — some data gap identified",extraTime:.35}],
    earlyFinish:{chance:.1,msg:"Recent clean backup available — restoration faster than expected"}},
   {id:"analyst_patch",name:"Patch the Entry Vulnerability (YOU)",team:"analyst",baseDuration:45,
    ocrRef:"1.3.1(c)",effectiveness:95,scorePts:120,
    description:"Personally patch the entry point the ransomware used to enter the network, preventing reinfection.",
    duringRisk:"You are unavailable to manage teams for ~45 seconds.",
    narrative:["Identifying the vulnerability used by the worm to propagate...","Examining lateral movement paths..."],
    complications:[],earlyFinish:{chance:.15,msg:"Known CVE with existing patch — quick deployment"},
    analystChallenge:{
      context:"Ransomware has encrypted files using asymmetric encryption. Even if you recover the files from backup, you need to understand WHY this encryption type makes ransomware so effective.",
      question:"Ransomware uses [blank] encryption. The victim receives only the PUBLIC key — which can ENCRYPT but NOT decrypt.\n\nType the encryption type (one word):",
      ocrLink:"OCR 1.3.1(c): Asymmetric encryption uses a KEY PAIR — a public key (shared freely) and a private key (kept secret). The public key can only encrypt. Only the private key can decrypt. This is why ransomware works: attackers give you the public key (so you can verify payment?) but keep the private key.",
      hint1:"It uses TWO different keys — one to encrypt, a different one to decrypt.",
      hint2:"The two types of encryption are SYMmetric (same key) and ________metric (different keys).",
      hint3:"ASYMMETRIC encryption. Public key encrypts (given to victim), private key decrypts (kept by attacker). This is what makes ransomware so effective.",
      fullAnswer:"asymmetric",
      checkFn:(s)=>s.trim().toLowerCase().includes("asymmetric")}}]},

 {id:"targeted_hospital",name:"Critical Infrastructure Attack",short:"Healthcare system targeted — patient safety at risk",
  escs:["CRITICAL: ransomware in clinical network — patient records at risk",
        "Appointment system offline — patients being turned away",
        "ICU MONITORING OFFLINE — emergency divert declared"],
  escR:10,uMin:5000,uMax:50000,spread:"Ransomware",
  responses:[
   {id:"emergency_isolate",name:"Emergency Clinical Isolation",team:"security",baseDuration:12,
    ocrRef:"1.3.3(c)",effectiveness:80,scorePts:80,
    description:"Immediately isolate clinical systems from infected administrative network.",
    duringRisk:"Administrative data continues to be encrypted during isolation.",
    narrative:[
      "CRITICAL INFRASTRUCTURE: highest priority isolation protocol activated.",
      "Clinical systems must be protected first — patient safety takes precedence.",
      "Segmenting clinical network from administrative systems — attack contained.",
      "Patient monitoring systems confirmed unaffected. Clinical operations continue."],
    complications:[{at:.4,chance:.3,msg:"Legacy clinical systems have unusual network topology — manual isolation",extraTime:.5}],
    earlyFinish:{chance:.1,msg:"Air gap between clinical and admin networks aided quick isolation"}},
   {id:"full_recovery",name:"Full Recovery + Backup Restore",team:"security",baseDuration:80,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:100,
    description:"Isolate, kill ransomware, restore from backup, return all systems to operational status.",
    duringRisk:"80 seconds of downtime. Some patient appointments must be rescheduled.",
    narrative:[
      "Executing full recovery protocol for critical infrastructure attack...",
      "Healthcare ransomware attacks have caused patient deaths — time is critical (1.3.3c).",
      "Encryption process terminated across all infected administrative machines.",
      "Clean backup from last night deployed. Patient data intact.",
      "Appointment system restored. Diverted patients being recalled."],
    complications:[{at:.5,chance:.35,msg:"Backup server also affected — using off-site copy",extraTime:.45}],
    earlyFinish:{chance:.05,msg:"Off-site backup was more recent than expected"}}]},

 {id:"double_extortion",name:"Double Extortion Ransomware",short:"Files encrypted AND data being exfiltrated for publication",
  escs:["Encrypting files AND exfiltrating data to attacker's server",
        "200GB already stolen — ransom note issued",
        "PUBLICATION THREAT: pay within 72hrs or data goes public"],
  escR:16,uMin:1000,uMax:20000,spread:"Credential Stuffing",
  responses:[
   {id:"cut_exfil",name:"Cut Exfiltration Channel",team:"network",baseDuration:20,
    ocrRef:"1.3.3(c)",effectiveness:75,scorePts:65,
    description:"Block the attacker's data exfiltration channel. Stops more data leaving — encryption continues.",
    duringRisk:"Files continue to be encrypted while the exfil channel is blocked.",
    narrative:[
      "Network Team identifying outbound data exfiltration channel...",
      "Double extortion: encrypt files AND steal data — two leverage points against victim (1.3.3c).",
      "Identifying C2 (Command & Control) server receiving stolen data.",
      "Firewall rule blocking outbound connection to 194.x.x.x. Data exfiltration stopped.",
      "Note: files still being encrypted — Security Ops needed for full eradication."],
    complications:[{at:.5,chance:.2,msg:"Attacker using CDN for exfil — harder to block",extraTime:.35}],
    earlyFinish:{chance:.15,msg:"Single exfil endpoint — quickly blocked"}},
   {id:"full_response",name:"Full: Cut Exfil + Isolate + Restore",team:"security",baseDuration:70,
    ocrRef:"1.3.3(c) + 1.3.1(c)",effectiveness:100,scorePts:100,
    description:"Complete response to double extortion: stop exfiltration, isolate, restore files.",
    duringRisk:"70 seconds of active attack — some additional data may be stolen.",
    narrative:[
      "Executing full double extortion response...",
      "Blocking exfiltration channel — data theft stopped.",
      "Isolating all infected machines — encryption halted.",
      "Restoring from last clean backup. Incident documented for potential GDPR notification.",
      "Note: data already exfiltrated cannot be recovered. Legal team notified of possible breach."],
    complications:[{at:.5,chance:.25,msg:"Ransomware group operating from multiple C2 nodes",extraTime:.3}],
    earlyFinish:{chance:.1,msg:"Attacker infrastructure had poor opsec — quick takedown"}}]}
]};
})();
