;(function(){
if(!window.CW_MODULES)window.CW_MODULES={};
window.CW_MODULES['SQL Injection']={
icon:"💉",cat:"Web Attack",col:"#44bbff",
explain:["ATTACK: SQL INJECTION  |  OCR 1.3.2(d) + 1.3.3(c)","━━━━━━━━━━━━━━━━━━━━━",
  "Attackers inject SQL commands into input fields, manipulating database queries.",
  "OCR DIRECT LINK (1.3.2d): Classic: ' OR 1=1 -- in a login box bypasses authentication.",
  "Fix: parameterised queries treat input as DATA, never as executable CODE.","Input validation also rejects suspicious characters."],
mutations:[
  {name:"Automated scanner",label:"🤖 AUTOMATED SCAN",escMulti:0.9,spreadMult:1.2,userMult:1.5},
  {name:"APT group",label:"🏴 APT GROUP",escMulti:1.5,spreadMult:1.8,userMult:2.0},
  {name:"Ransomware pre-stage",label:"💰 PRE-RANSOMWARE",escMulti:1.2,spreadMult:1.6,userMult:1.3}],
scenarios:[
 {id:"login_bypass",name:"SQLi Login Bypass",short:"Authentication bypassed via injected OR 1=1 clause",
  escs:["SQLi bypass attempts detected — login form vulnerable",
        "Admin authentication bypassed — database being explored",
        "FULL DATABASE ACCESS — all user records exposed"],
  escR:32,uMin:200,uMax:30000,spread:"Credential Stuffing",
  responses:[
   {id:"waf_block",name:"Deploy WAF Rules",team:"network",baseDuration:22,
    ocrRef:"1.3.3(c)",effectiveness:75,scorePts:60,
    description:"Deploy Web Application Firewall rules to block common SQL injection patterns. Fast but doesn't fix the root cause.",
    duringRisk:"Code remains vulnerable — an adapted injection could bypass WAF rules.",
    narrative:[
      "Network Team deploying WAF (Web Application Firewall) rules...",
      "WAF inspects HTTP traffic and blocks requests matching known attack patterns.",
      "SQL injection patterns detected: ' OR 1=1, UNION SELECT, DROP TABLE — all blocked.",
      "This is a temporary fix. The underlying vulnerability in the code still exists.",
      "WAF active. Attack traffic blocked. Development team must patch the actual query."],
    complications:[{at:.5,chance:.3,msg:"Attacker adapted injection to bypass initial WAF rules",extraTime:.4}],
    earlyFinish:{chance:.1,msg:"Standard injection patterns — pre-built WAF ruleset applied quickly"}},
   {id:"patch_queries",name:"Patch: Parameterise Queries (YOU)",team:"analyst",baseDuration:50,
    ocrRef:"1.3.2(d)",effectiveness:100,scorePts:130,
    description:"YOU personally patch the vulnerable code using parameterised queries — the permanent, correct fix from the OCR spec.",
    duringRisk:"You are unavailable for ~50 seconds. DB remains exploitable until you finish.",
    narrative:[
      "Loading the vulnerable authentication code...",
      "Parameterised queries (prepared statements) fix SQL injection at the source (OCR 1.3.2d).",
      "Input is passed as a PARAMETER, not concatenated into the query string."],
    complications:[],earlyFinish:{chance:.2,msg:"Simple single-endpoint vulnerability — quick patch"},
    analystChallenge:{
      context:"The vulnerable login query is: SELECT * FROM users WHERE email='\" + email + \"'\n\nThis lets attackers inject SQL. The OCR spec fix is parameterised queries, where inputs are treated as DATA not CODE.",
      question:"Complete the fixed parameterised query:\n\nSELECT * FROM users WHERE email = ___\n\n(Type the placeholder symbol used in parameterised queries):",
      ocrLink:"OCR 1.3.2(d): SQL injection occurs when user input is concatenated directly into SQL queries. The fix is PARAMETERISED QUERIES (also called prepared statements) — the query structure is defined first, then data is passed separately as a parameter using a ? placeholder. The database engine treats the input as pure data, never as executable SQL.",
      hint1:"In parameterised queries, you use a placeholder symbol instead of the actual value. It's a single punctuation character.",
      hint2:"The placeholder is a question mark. The query becomes: WHERE email = ? and the actual value is passed separately.",
      hint3:"The answer is ? — a question mark. Full query: SELECT * FROM users WHERE email = ? — then the email value is bound separately, so the database treats it as data, not SQL code.",
      fullAnswer:"?",
      checkFn:(s)=>s.trim()==="?"||s.toLowerCase().includes("question mark")||s.includes("$1")||s.includes(":email")}}]},

 {id:"data_extraction",name:"SQLi Data Extraction",short:"UNION-based attack dumping entire database tables",
  escs:["UNION SELECT injection extracting user table data",
        "Customer PII being exfiltrated — GDPR breach imminent",
        "ENTIRE DATABASE DUMPED — 2.1M customer records stolen"],
  escR:38,uMin:1000,uMax:80000,spread:"Credential Stuffing",
  responses:[
   {id:"emergency_patch",name:"Emergency Input Validation",team:"security",baseDuration:28,
    ocrRef:"1.3.2(d)",effectiveness:80,scorePts:70,
    description:"Add server-side input validation to reject characters used in SQL injection attacks.",
    duringRisk:"Extraction continues until validation is deployed.",
    narrative:[
      "Security Ops deploying emergency input validation rules...",
      "Input validation rejects suspicious characters before they reach the SQL query.",
      "Characters blocked: single quotes, double-dashes, semicolons, UNION keyword.",
      "This stops the current attack but parameterised queries are still needed for full fix.",
      "Extraction stopped. GDPR breach team notified of potential data exposure."],
    complications:[{at:.5,chance:.25,msg:"Attacker encoding characters to bypass simple validation",extraTime:.35}],
    earlyFinish:{chance:.1,msg:"Simple character blacklist sufficient for this attacker's technique"}},
   {id:"analyst_fix",name:"Full Parameterisation Fix (YOU)",team:"analyst",baseDuration:55,
    ocrRef:"1.3.2(d)",effectiveness:100,scorePts:130,
    description:"Permanently fix ALL database queries across the codebase using parameterised queries.",
    duringRisk:"You are unavailable for ~55 seconds.",
    narrative:["Auditing all database query entry points in the codebase...","Applying parameterised query pattern across all endpoints..."],
    complications:[],earlyFinish:{chance:.1,msg:"Queries followed a standard pattern — batch fix applied"},
    analystChallenge:{
      context:"A UNION SELECT attack is extracting data: the attacker added ' UNION SELECT email,password FROM users-- to a search query. What database concept prevents this by treating input as data?",
      question:"What is the name of the OCR-specified technique that passes user input as a PARAMETER rather than part of the query string?\n\n(Two words — the OCR spec name for the fix):",
      ocrLink:"OCR 1.3.2(d): Parameterised queries (also called prepared statements) are the definitive defence against SQL injection. The SQL structure is compiled first — then user input is passed as a separate parameter. The database engine cannot interpret the input as SQL commands, regardless of what characters it contains.",
      hint1:"OCR 1.3.2(d) names a specific technique. It's the opposite of 'concatenating strings'.",
      hint2:"The input is passed as a __________ (not part of the query string). The technique is called __________ queries.",
      hint3:"PARAMETERISED QUERIES — also called prepared statements. The query template is compiled first, then values are bound separately.",
      fullAnswer:"parameterised queries",
      checkFn:(s)=>{const l=s.toLowerCase();return l.includes("parameteris")||l.includes("parameteri")||l.includes("prepared statement");}}}]},

 {id:"blind_sqli",name:"Blind SQL Injection",short:"Time-based inference attack — slow but extracts full schema",
  escs:["Time-delay SQL injection mapping database schema",
        "Attacker has full schema — now extracting credentials",
        "ADMIN PASSWORD HASH EXTRACTED — cracking in progress"],
  escR:45,uMin:500,uMax:40000,spread:"Brute Force",
  responses:[
   {id:"block_delays",name:"Block Time-Based Requests",team:"network",baseDuration:20,
    ocrRef:"1.3.2(d)",effectiveness:70,scorePts:55,
    description:"Set server-side timeouts that break time-delay injection techniques.",
    duringRisk:"Attacker may switch to boolean-based blind injection instead.",
    narrative:[
      "Blind SQL injection uses intentional time delays to infer data without seeing output.",
      "If database takes 5s to respond → condition was true. Instant response → false.",
      "Configuring maximum query execution time: 1 second hard limit.",
      "Time-based injection now impossible. Boolean-based attacks still need parameterisation."],
    complications:[{at:.5,chance:.2,msg:"Some legitimate queries also use longer execution — adjusting threshold",extraTime:.3}],
    earlyFinish:{chance:.15,msg:"Simple timeout configuration applied quickly"}},
   {id:"analyst_audit",name:"Full Code Audit + Fix (YOU)",team:"analyst",baseDuration:60,
    ocrRef:"1.3.2(d)",effectiveness:100,scorePts:130,
    description:"Audit all database interactions and apply parameterised queries across the entire codebase.",
    duringRisk:"You are unavailable for ~60 seconds.",
    narrative:["Running automated SQLi vulnerability scanner across all endpoints...","Cataloguing all unparameterised queries for systematic patching..."],
    complications:[],earlyFinish:{chance:.1,msg:"Small codebase — audit completed quickly"},
    analystChallenge:{
      context:"Blind SQL injection doesn't return visible data — instead it asks true/false questions using timing or boolean logic. E.g., IF(1=1, SLEEP(5), 0) — if the database sleeps 5 seconds, the condition was true.",
      question:"What character begins most SQL injection attacks, breaking out of the intended query string?\n\nType the single character:",
      ocrLink:"OCR 1.3.2(d): SQL injection exploits applications that concatenate user input directly into SQL queries. The single quote character (') is used to break out of the string context in the query. For example: WHERE name='[input]' becomes WHERE name='' OR 1=1--' when ' OR 1=1-- is injected.",
      hint1:"It's a punctuation character used in SQL to delimit strings.",
      hint2:"SQL uses this character to start and end text strings. Type it directly — it's one character.",
      hint3:"A single quote: ' — this breaks the SQL string context and allows injection of arbitrary SQL commands.",
      fullAnswer:"'",
      checkFn:(s)=>s.trim()==="\'"||s.toLowerCase().includes("single quote")||s.toLowerCase().includes("apostrophe")}}]}
]};
})();
