;(function(){
if(!window.CW_MODULES)window.CW_MODULES={};
window.CW_MODULES['Trojan Backdoor']={
icon:"🐴",cat:"Malware",col:"#cc44ff",
explain:["ATTACK: TROJAN  |  OCR 1.3.3(c)","━━━━━━━━━━━━━━━━━━━━━",
  "OCR DISTINCTIONS: Trojan = disguised as legit software, does NOT self-replicate.",
  "Virus = attaches to files, DOES self-replicate. Worm = spreads autonomously.",
  "C2 (Command & Control): attacker's server sends commands to infected machines (botnet)."],
mutations:[
  {name:"Nation-state APT",label:"🏴 APT GROUP",escMulti:1.7,spreadMult:2.0,userMult:1.5},
  {name:"Commercial RAT",label:"💼 COMMERCIAL RAT",escMulti:1.1,spreadMult:1.3,userMult:1.2},
  {name:"Pre-ransomware",label:"💰 PRE-RANSOMWARE",escMulti:1.4,spreadMult:1.8,userMult:1.3}],
scenarios:[
 {id:"rat",name:"Remote Access Trojan",short:"Full remote control backdoor — attacker has keyboard, screen, files",
  escs:["C2 beacon traffic detected — RAT installed, calling home",
        "Data exfiltration confirmed — attacker browsing file shares remotely",
        "APT: full network visibility, privilege escalation in progress"],
  escR:45,uMin:100,uMax:5000,spread:"Trojan Backdoor",
  responses:[
   {id:"c2_block",name:"Block C2 Beacon Traffic",team:"network",baseDuration:18,
    ocrRef:"1.3.3(c)",effectiveness:75,scorePts:60,
    description:"Block the malware's communication with its Command & Control server, blinding the attacker.",
    duringRisk:"RAT remains on machine — attacker loses control but malware is still present.",
    narrative:[
      "Network Team identifying C2 (Command & Control) beacon traffic...",
      "Trojans 'call home' to C2 servers for instructions — OCR 1.3.3(c) botnet concept.",
      "C2 communication identified: periodic 30-second beacons to 94.142.x.x.",
      "Firewall rule deployed — C2 traffic blocked. Attacker loses remote control.",
      "Note: trojan still installed. Security Ops needed for full removal."],
    complications:[{at:.5,chance:.25,msg:"Malware using domain-generation algorithm — C2 rotating",extraTime:.35}],
    earlyFinish:{chance:.1,msg:"C2 server on known threat intelligence list — quick block"}},
   {id:"full_eradication",name:"Scan + Isolate + Wipe",team:"security",baseDuration:60,
    ocrRef:"1.3.3(c)",effectiveness:100,scorePts:100,
    description:"Full eradication: scan network for all infected hosts, isolate, then clean reinstall.",
    duringRisk:"Attacker has full access for 60 seconds during scan.",
    narrative:[
      "Security Ops executing full RAT eradication protocol...",
      "A Trojan disguises itself as legitimate software — OCR 1.3.3(c).",
      "Scanning for C2 beacon patterns across all 450 machines...",
      "7 infected hosts identified. All isolated from network.",
      "Malware persists through patching — clean reinstall required.",
      "Full OS reinstall deployed from verified media. Backdoor permanently removed.",
      "Credentials rotated. Access logs audited for data exfiltration evidence."],
    complications:[{at:.4,chance:.3,msg:"Malware had rootkit component — harder to detect and remove",extraTime:.45}],
    earlyFinish:{chance:.05,msg:"Known malware family — specialist removal tool applied quickly"}},
   {id:"analyst_forensics",name:"Digital Forensics (YOU)",team:"analyst",baseDuration:50,
    ocrRef:"1.3.3(c)",effectiveness:90,scorePts:120,
    description:"Conduct forensic analysis to understand how the trojan entered and what data was accessed.",
    duringRisk:"You are unavailable for ~50 seconds.",
    narrative:["Examining infection vector — how did the trojan get onto this machine?"],
    complications:[],earlyFinish:{chance:.1,msg:"Clear audit trail — forensics completed quickly"},
    analystChallenge:{
      context:"A Trojan was found on 7 workstations. A colleague asks: 'Is it spreading by itself? Should we worry about it infecting other machines automatically?'",
      question:"A Trojan does NOT automatically spread to other computers. What type of malware DOES spread autonomously across networks without user action?\n\nType the one-word answer:",
      ocrLink:"OCR 1.3.3(c) distinguishes three types: TROJAN — disguises as legitimate software, requires user to run it, does NOT self-replicate. VIRUS — attaches to files, self-replicates, requires a host file. WORM — spreads autonomously across networks with NO user action needed. This distinction is directly testable in OCR exams.",
      hint1:"Unlike a trojan, this type spreads by itself across networks without needing a user to run anything.",
      hint2:"A _______ spreads autonomously across networks. Famous examples: WannaCry, Morris Worm.",
      hint3:"A WORM spreads autonomously — no user action needed. A trojan requires the user to run it. A virus needs a host file to replicate.",
      fullAnswer:"worm",
      checkFn:(s)=>s.trim().toLowerCase()==="worm"||s.toLowerCase().includes("worm")}}]},

 {id:"keylogger",name:"Keylogger Trojan",short:"All keystrokes captured and sent to attacker in real-time",
  escs:["Keylogger active — all typed passwords being captured",
        "Banking credentials sent to C2 server",
        "MASS CREDENTIAL THEFT — 340 accounts compromised in real time"],
  escR:38,uMin:50,uMax:8000,spread:"Credential Stuffing",
  responses:[
   {id:"isolate_scan",name:"Isolate + Scan + Remove",team:"security",baseDuration:35,
    ocrRef:"1.3.3(c)",effectiveness:90,scorePts:80,
    description:"Isolate infected machines, scan for keylogger processes, and remove the malware.",
    duringRisk:"Keystroke capture continues during isolation.",
    narrative:[
      "Keylogger trojans silently record every keystroke — passwords, emails, messages.",
      "Security Ops isolating machines with anomalous outbound data patterns.",
      "Keylogger process identified and terminated. C2 connection cut.",
      "Malware removed. All passwords captured during infection period must be rotated.",
      "MFA enforcement recommended — captured passwords alone won't be sufficient for access."],
    complications:[{at:.5,chance:.2,msg:"Keylogger had persistence mechanism — reinstalling after removal",extraTime:.35}],
    earlyFinish:{chance:.1,msg:"Keylogger used no persistence — single removal sufficient"}}]}
]};
})();
